Add Milestones section
l2beat/l2beat pull request #1006
Opened 2022-11-23 14:28 UTC by antooni

2022-11-24 08:59 UTC, michalsidzej commented on packages/frontend/src/components/project/Milestones.tsx
> +        </div>
Good job with placing svgs on top of this line. With the vertical line I have few ideas thou. You don't need to use absolute here, maybe 'flex' would be cleaner here?
```suggestion
      <div className='flex'>
        <div className="h-[100%] mt-2">
          <div className="h-[70%] w-[1px] bg-green-500 " />
          <div className="h-[30%] w-[1px] bg-gradient-to-b from-green-500" />
        </div>
```

2022-11-24 11:38 UTC, sz-piotr commented
I think that the bottom gradient line is also too low:
<img width="403" alt="Screenshot 2022-11-24 at 12 37 55" src="https://user-images.githubusercontent.com/17070569/203775366-067e0a85-ce9d-4cd1-87e2-1f219ca68180.png">

2022-11-24 11:40 UTC, sz-piotr commented
I also think that you need to use smaller gaps than in figma because the line height already provides some of that spacing

2022-11-25 09:19 UTC, michalsidzej commented on packages/frontend/src/components/project/Milestones.tsx
> +function transformDate(date: Date): string {
Maybe `formatDate`?

2022-11-25 09:24 UTC, michalsidzej requested changes

2022-11-25 09:24 UTC, michalsidzej commented on packages/frontend/src/components/project/Milestones.tsx
> +              <MilestoneIcon className=" absolute left-[6px] fill-green-200 stroke-green-400 dark:fill-green-800 dark:stroke-green-500" />
```suggestion
              <MilestoneIcon className="absolute left-1.5 fill-green-200 stroke-green-400 dark:fill-green-800 dark:stroke-green-500" />
```

2022-11-25 09:24 UTC, michalsidzej commented on packages/frontend/src/components/project/Milestones.tsx
> +              <div className="font-bold text-[18px] leading-[18px]">
```suggestion
              <div className="font-bold text-lg leading-none">
```

2022-11-25 09:24 UTC, michalsidzej commented on packages/frontend/src/components/project/Milestones.tsx
> +                  <div className="dark:text-gray-400 text-[15px] leading-[15px]">
```suggestion
                  <div className="dark:text-gray-400 text-sm leading-none">
```

2022-11-25 09:24 UTC, michalsidzej commented on packages/frontend/src/components/project/Milestones.tsx
> +          <div className="h-[35%] w-[1.7px] dark:w-[1px] bg-gradient-to-b from-green-400 dark:from-green-500" />
```suggestion
          <div className="h-[60%] w-[1.7px] dark:w-px bg-green-400 dark:bg-green-500 " />
          <div className="h-[35%] w-[1.7px] dark:w-px bg-gradient-to-b from-green-400 dark:from-green-500" />
```

2022-11-25 13:17 UTC, michalsidzej commented on packages/frontend/src/components/project/Milestones.tsx
> +function formatDate(date: Date): string {
```suggestion
}

function formatDate(date: Date): string {
```

2022-11-25 13:17 UTC, michalsidzej commented on packages/frontend/src/components/project/Milestones.tsx
> +function getEnding(days: number) {
Maybe `getOrdinalSuffix`

2022-11-25 13:17 UTC, michalsidzej commented on packages/frontend/src/components/icons/Arrows.tsx
> +        fill-rule="evenodd"
`fillRule`, Otherwise we get warnings from React

2022-11-25 13:17 UTC, michalsidzej commented on packages/frontend/src/components/icons/Arrows.tsx
> +        clip-rule="evenodd"
`clipRule`

2022-11-25 13:19 UTC, michalsidzej commented on packages/frontend/src/components/project/Milestones.tsx
> +        </div>
@antooni What about this one? I'm not a fan of this 15.4px here

2022-11-25 14:56 UTC, michalsidzej approved these changes

2022-11-25 16:04 UTC, sz-piotr approved these changes

2022-11-28 08:58 UTC, merged