Show milestones on main page
l2beat/l2beat pull request #1056
Opened 2022-12-09 15:25 UTC by antooni

2022-12-12 15:46 UTC, krzkaczor requested changes

2022-12-12 15:46 UTC, krzkaczor commented on packages/config/src/layer2s/common/milestones.ts
> +      'Optimism sof launch is live, bringing first universal rollup based on optimistic architecture.',
sof -> soft typo

2022-12-12 15:46 UTC, krzkaczor commented on packages/config/src/layer2s/common/milestones.ts
> +    name: 'ZK Rollup (privacy)',
old: ZK Rollup (privacy)
new: ZK Rollup (privacy/payments) 
alternative version: ZK Rollup (anonymous payments)

2022-12-13 08:47 UTC, luke7211 approved these changes

2022-12-13 08:47 UTC, luke7211 commented on packages/config/src/layer2s/common/milestones.ts
> +    name: 'ZK rollup (payments)',
First zkRollup (for payments)

2022-12-13 08:47 UTC, luke7211 commented on packages/config/src/layer2s/common/milestones.ts
> +    name: 'Optimistic Rollup (payments)',
First fully-trustless Optimistic Rollup (for payments)

2022-12-13 08:47 UTC, luke7211 commented on packages/config/src/layer2s/common/milestones.ts
> +    name: 'Optimistic Rollup (universal)',
First generalised Optimistic Rollup with fraud proofs

2022-12-13 08:47 UTC, luke7211 commented on packages/config/src/layer2s/common/milestones.ts
> +    name: 'Public Optimistic Rollup (universal)',
First permissionless, generalised Optimistic Rollup open to anyone

2022-12-13 08:47 UTC, luke7211 commented on packages/config/src/layer2s/common/milestones.ts
> +    name: 'ZK Rollup (anonymous payments)',
First privacy-focused Zk Rollup (payments)

2022-12-13 12:58 UTC, merged