Add database per request logging, improve existing wrap methods
l2beat/l2beat pull request #1114
Opened 2023-01-10 20:35 UTC by krzkaczor

I decided to make mutating methods of repositories log to info level instead of debug.

btw. it should be possible to replace manual wrapping with "automatic" one in the constructor of `BaseRepository`.

2023-01-10 20:36 UTC, krzkaczor commented on packages/backend/src/peripherals/database/shared/BaseRepository.ts
> +    return this.wrap(fn, log)
addMany methods weren't tracked in metrics 😨 CC: @michalsidzej

2023-01-13 08:33 UTC, sz-piotr requested changes

2023-01-13 08:33 UTC, sz-piotr commented on packages/backend/src/peripherals/database/shared/BaseRepository.ts
> +      this.logger.info({ method: method.name, id: id.valueOf() }),
Using info will produce too many logs for papertrail, so it's actually not useful because we'll get cut off early

2023-01-13 08:49 UTC, sz-piotr requested changes

2023-01-13 08:49 UTC, sz-piotr commented on packages/backend/src/Application.ts
> +        if (config.logger.logLevel >= LogLevel.DEBUG) {
Move this check to `database.enableQueryLogging()`

2023-01-16 08:22 UTC, sz-piotr approved these changes

2023-01-16 08:22 UTC, merged