Add repository to DiscoveryWatcher
l2beat/l2beat pull request #1124
Opened 2023-01-18 18:11 UTC by antooni

This PR aims to add repository storing recent changes to the discovery output, thanks to it we will not duplicate discord notifications.

Resolves L2B-360

2023-01-20 13:41 UTC, michalsidzej commented on packages/backend/src/peripherals/discord/DiscordClient.ts
> +      throw new Error(`Discord error: Message size exceeded (2000 characters)`)
```suggestion
      throw new Error(`Discord error: Message size exceeded (${MAX_MESSAGE_LENGTH} characters)`)
```

2023-01-30 11:29 UTC, michalsidzej commented on packages/backend/src/core/DiscoveryWatcher.ts
> +    }
```suggestion
    const currentContracts = databaseEntry.length === 0 ? committed.contracts : databaseEntry[0].discovery.contracts
    const diff = diffDiscovery(
      currentContracts,
      parsedDiscovery.contracts,
      overrides ?? {},
    )
```

Would be even better if you could get currentContracts from a separate method

2023-01-30 13:21 UTC, michalsidzej commented on packages/backend/src/core/DiscoveryWatcher.test.ts
> +      expect(discordClient.sendMessage).toHaveBeenCalledExactlyWith([])
Hmm, is that right? Do we want to send and empty message?

2023-01-30 13:45 UTC, michalsidzej requested changes

2023-01-30 13:45 UTC, michalsidzej commented on packages/backend/src/peripherals/database/discovery/DiscoveryWatcherRepository.ts
> +    ) as ProjectParameters,
```suggestion
    discovery: row.discovery_json_blob as unknown as ProjectParameters
```
No need to parse JSON here, knex is doing it for you already

2023-01-30 13:45 UTC, michalsidzej commented on packages/backend/src/peripherals/database/discovery/DiscoveryWatcherRepository.ts
> +  async getLatest(name: string): Promise<DiscoveryWatcherRecord[]> {
why not `findLatest` here and return a single value?

2023-01-31 11:00 UTC, michalsidzej approved these changes
Two small comments, but it's fine

2023-01-31 11:00 UTC, michalsidzej commented on packages/backend/src/core/DiscoveryWatcher.ts
> +      : committed.contracts
We can skip reading local files until we know that the repository returned undefined.

2023-01-31 11:00 UTC, michalsidzej commented on packages/backend/src/core/DiscoveryWatcher.ts
> +    return diff
No need to save it as a variable here

2023-01-31 11:56 UTC, sz-piotr commented on packages/backend/src/core/DiscoveryWatcher.ts
> +      : (await this.configReader.readDiscovery(name)).contracts
In another PR: We should add config hash to discovery output so that if config changes we always prioritize discovery from disk.

2023-01-31 11:56 UTC, sz-piotr approved these changes

2023-01-31 12:22 UTC, merged