Add monitor and milestones to boba
l2beat/l2beat pull request #1136
Opened 2023-01-24 08:34 UTC by luke7211

2023-01-25 09:44 UTC, antooni commented
There are some contracts listed on L2Beat that are missing in discovered.json:

https://etherscan.io/address/0xC891F466e53f40603250837282eAE4e22aD5b088
https://etherscan.io/address/0x1A26ef6575B7BBB864d984D9255C069F6c361a14
https://etherscan.io/address/0x5fD2CF99586B9D92f56CbaD0A3Ea4DF256A0070B

2023-01-25 09:55 UTC, michalsidzej approved these changes

2023-01-25 10:04 UTC, michalsidzej requested changes
Some changes that we can see in the discovery should be updated in the config
L1MultiMessageRelayer is missing now
L1LiquidityPool, L1NFTBridge changed address

2023-01-27 08:58 UTC, luke7211 commented
> Some changes that we can see in the discovery should be updated in the config L1MultiMessageRelayer is missing now L1LiquidityPool, L1NFTBridge changed address

Missing contracts added

2023-02-01 17:46 UTC, antooni requested changes
Milestones:
- Boba launches L2 on BNB
- Boba launches L2 on Avalanche
- Boba launches L2 on Moonbeam and Fantom

do not  qualify as milestones because it seems like a regular deployment on EVM compatible chain, correct me if I am wrong

2023-02-01 17:49 UTC, michalsidzej approved these changes

2023-02-01 17:51 UTC, michalsidzej approved these changes
Please respond to Antoni's request. Otherwise LGTM

2023-02-02 09:26 UTC, luke7211 commented on packages/config/src/layer2s/bobanetwork.ts
> +      name: 'Boba launches L2 on BNB',
This is, for Boba, a significant milestone given their strategy. We are not tracking Boba on other chains, however this milestone explains removal a significant chunk of BOBA tokens from Ethereum Rollup

2023-02-02 09:44 UTC, antooni approved these changes

2023-02-02 10:04 UTC, merged