Add config hash to discovery
l2beat/l2beat pull request #1170
Opened 2023-02-02 14:47 UTC by antooni

Resolves L2B-732

2023-02-03 12:59 UTC, torztomasz requested changes

2023-02-03 12:59 UTC, torztomasz commented on packages/backend/src/core/discovery/runDiscovery.ts
>    const projectConfig = await configReader.readConfig(config.project)
I am thinking about extracting configReader to common package as I am also reading discovery in deriving

2023-02-06 16:22 UTC, torztomasz approved these changes

2023-02-06 17:18 UTC, michalsidzej commented on packages/backend/src/core/discovery/utils/diffDiscovery.ts
> +}
```suggestion
function getIgnored(
  address: EthereumAddress,
  overrides?: Partial<Record<string, DiscoveryContract>>,
): string[] {
  if (overrides === undefined) {
    return []
  }

  const override = overrides[address.toString()]
  if (override === undefined) {
    return []
  }

  return override.ignoreInWatchMode ?? []
}
```

2023-02-06 17:21 UTC, michalsidzej commented on packages/backend/src/core/discovery/utils/diffDiscovery.ts
> +    const ignored: string[] = getIgnored(committedContract.address, overrides)
```suggestion
    const ignored = getIgnored(committedContract.address, overrides)
```

2023-02-06 17:22 UTC, michalsidzej commented on packages/backend/src/core/DiscoveryWatcher.ts
> +    }
No need to use `if...else` if you are returning

2023-02-06 17:25 UTC, michalsidzej requested changes
Comments above

2023-02-07 08:25 UTC, michalsidzej commented on packages/backend/src/core/DiscoveryWatcher.ts
> +    }
this could be one statement with logical alternative

2023-02-07 09:10 UTC, michalsidzej approved these changes

2023-02-07 10:58 UTC, merged

2023-02-07 11:49 UTC, sz-piotr commented on packages/backend/src/core/discovery/utils/getDiscoveryConfigHash.ts
> +}
How about a different approach: In config reader whenever you read the config the file contents are both parsed and hashed and the result is `{ ...parsed, hash}`. That way the config hash is actually just the hash of the config file including comments, whitespace, etc. Any change to the config file requires re-running discovery.
@michalsidzej @antooni