Implement Archived Projects
l2beat/l2beat pull request #1232
Opened 2023-02-21 14:24 UTC by michalsidzej

Resolves L2B-629

2023-02-22 09:00 UTC, luke7211 commented on packages/config/src/layer2s/hermez.ts
> +  isArchived: true,
I don't think Hermez is archived at this stage

2023-02-22 09:40 UTC, luke7211 commented on packages/config/src/layer2s/hermez.ts
> +  isArchived: true,
No, Fuel is definitely not archived, it's up and running as we have experienced

2023-02-22 11:02 UTC, antooni commented on packages/frontend/src/components/table/props/getBridgesRowProps.ts
> +    'data-layer2': entry.type !== 'bridge' ? true : undefined,
A comment would be useful there

2023-02-22 11:05 UTC, antooni requested changes
Is this view on mobile desired?
<img width="493" alt="image" src="https://user-images.githubusercontent.com/72789647/220602347-ff6907c4-53f5-48f1-91b0-0b09aa456e97.png">

2023-02-22 18:31 UTC, michalsidzej commented on packages/frontend/src/components/table/props/getBridgesRowProps.ts
> +    'data-layer2': entry.type !== 'bridge' ? true : undefined,
Changed it, do you like it now?

2023-02-23 10:42 UTC, antooni approved these changes

2023-02-24 10:07 UTC, merged