Replace "project archived" icon
l2beat/l2beat pull request #1270
Opened 2023-03-06 14:12 UTC by vitali-l2beat

Resolves L2B-937
https://linear.app/l2beat/issue/L2B-937/replace-project-archived-icon-on-details-page

2023-03-07 05:51 UTC, michalsidzej requested changes

2023-03-07 05:51 UTC, michalsidzej commented on packages/frontend/src/components/project/Callout.tsx
> +      <span className={cx('flex items-center')}>{icon}</span>
Changes in this component caused many undesired layout shifts (check out the storybook-visual-regression). IMO, we could use a new simple component with a background and icon, that will be only responsible for the "project archived" warning. No need to complicate the warning bar then.

2023-03-08 09:35 UTC, michalsidzej commented on packages/frontend/src/components/project/WarningBar.tsx
> +          <ArchivedIcon className={cx()} />
```suggestion
          <ArchivedIcon />
```

2023-03-08 09:35 UTC, michalsidzej commented on packages/frontend/src/components/project/ArchivedBar.tsx
> +export function ArchivedBar({ text, className }: ArchiveBarProps) {
```suggestion
export function ArchivedBar({ text }: ArchiveBarProps) {

```

2023-03-08 09:35 UTC, michalsidzej commented on packages/frontend/src/components/project/ArchivedBar.tsx
> +}
```suggestion
export interface ArchiveBarProps {
  text: string
}

```

2023-03-08 09:35 UTC, michalsidzej commented on packages/frontend/src/components/project/ArchivedBar.tsx
> +      className={cx('bg-gray-750 flex justify-center rounded-lg', className)}
```suggestion
      className='bg-gray-750 flex justify-center rounded-lg'

```

2023-03-08 09:35 UTC, michalsidzej commented on packages/frontend/tailwind.config.js
>          800: '#424242',
Are you sure we need that? It's okay to change the color slightly if we have a similar in the codebase already.

2023-03-08 11:29 UTC, antooni commented on packages/frontend/src/components/project/WarningBar.tsx
> +  isArchived?: boolean
This one is not needed any more

2023-03-08 11:30 UTC, antooni commented on packages/frontend/src/components/project/ArchivedBar.tsx
> +export function ArchivedBar({ text }: ArchiveBarProps) {
Add storybook for this component

2023-03-08 11:30 UTC, antooni commented on packages/frontend/src/components/header/DetailsHeader.tsx
> +          <ArchivedBar text="This project is archived and no longer maintained." />
Add storybook for details with archive bar

2023-03-08 11:31 UTC, antooni requested changes
Add new UI elements to storybook

2023-03-08 13:03 UTC, michalsidzej approved these changes

2023-03-08 13:03 UTC, michalsidzej commented on packages/frontend/src/components/project/ArchivedBar.tsx
> +        'rounded-lg bg-gray-800 py-2.5',
```suggestion
        'mb-6 flex justify-center p-2.5 md:px-0',
        'rounded-lg bg-gray-800',
```

2023-03-08 13:09 UTC, michalsidzej requested changes
The light mode implementation doesn't look quite right. 
<img width="1198" alt="Screenshot 2023-03-08 at 14 08 36" src="https://user-images.githubusercontent.com/38423054/223721479-609135ae-c4dc-42fe-8353-959d8c3e2604.png">

2023-03-09 07:35 UTC, michalsidzej commented on packages/frontend/src/components/project/ArchivedBar.tsx
> +        <span className="ml-2 text-base font-medium dark:text-white">
```suggestion
        <span className="ml-2 text-base font-medium">
```
Is it necessary? Text defaults to white on dark mode

2023-03-09 07:35 UTC, michalsidzej commented on packages/frontend/src/components/project/ArchivedBar.tsx
> +        'mb-6 flex justify-center py-2.5 md:px-0',
I'm not sure what's your goal with `md:px-0` (px is 0 already, as it's never set to a value).

2023-03-09 10:10 UTC, michalsidzej approved these changes
LGTM

2023-03-09 11:11 UTC, antooni approved these changes

2023-03-09 11:17 UTC, merged