Add navigation to faq page
l2beat/l2beat pull request #1450
Opened 2023-05-07 16:46 UTC by torztomasz

Resolves L2B-963

2023-05-08 14:10 UTC, krzkaczor approved these changes

2023-05-08 15:05 UTC, antooni requested changes
Maybe we should make the navigation menu sticky, the same as on the project detail?

2023-05-08 17:08 UTC, torztomasz commented
> Maybe we should make the navigation menu sticky, the same as on the project detail?

The navigation is overflowing on smaller screens. That's why it is not possible.

2023-05-09 07:54 UTC, antooni approved these changes

2023-05-09 09:53 UTC, merged