Add `ChainId` discriminator to balances status
l2beat/l2beat pull request #1650
Opened 2023-07-10 15:04 UTC by sdlyy

Resolves L2B-1785

## Context
Yet another part of handling more than one chain. 

## Changes
- Added `chainId` column to `balances_status`
- Added `chainId` selector param for `BalanceStatusRepository`
- Adjusted subsequent uses of repository methods

2023-07-10 18:53 UTC, Inatiye0911905991 commented
4b7681a6fe83af15f3a82e781fe59c815b65be04

2023-07-11 10:04 UTC, antooni requested changes

2023-07-11 10:44 UTC, sdlyy commented on packages/backend/src/peripherals/database/migrations/063_balances_status_chain_id.ts
> +    table.primary(['chain_id', 'unix_timestamp', 'config_hash'])
https://github.com/l2beat/l2beat/pull/1650/commits/8e7eb8e23118b15f0d0c53a1b3dd325cb8e54159

2023-07-11 10:44 UTC, sdlyy commented on packages/backend/src/peripherals/database/migrations/063_balances_status_chain_id.ts
> +
https://github.com/l2beat/l2beat/pull/1650/commits/8e7eb8e23118b15f0d0c53a1b3dd325cb8e54159

2023-07-11 10:44 UTC, sdlyy commented on packages/backend/src/peripherals/database/migrations/063_balances_status_chain_id.ts
https://github.com/l2beat/l2beat/pull/1650/commits/ef14735a65fd8f16c7892c9d61052717c9ce4811

2023-07-11 11:16 UTC, antooni commented on packages/backend/src/peripherals/database/BalanceStatusRepository.test.ts
> +  const CHAIN_ID = ChainId.ETHEREUM
imo the tests are more readable when you inline this value

2023-07-11 11:17 UTC, antooni reviewed
looks good, I will do the migration on my local machine and give you the approve

2023-07-11 12:21 UTC, antooni approved these changes

2023-07-11 13:25 UTC, merged