Add escapeVerifier to Apex discovery
l2beat/l2beat pull request #1672
Opened 2023-07-16 11:32 UTC by adamiak

2023-07-16 11:42 UTC, lucadonnoh requested changes
LGTM, can you also add the contract to the ts file?

2023-07-17 20:18 UTC, luke7211 approved these changes

2023-07-18 10:14 UTC, antooni commented
![image](https://github.com/l2beat/l2beat/assets/72789647/deb8fb3e-cb40-47f8-b856-3f16964f64f8)

2023-07-18 10:17 UTC, lucadonnoh approved these changes

2023-07-19 06:32 UTC, merged