Add TVL tooltips
l2beat/l2beat pull request #1714
Opened 2023-07-24 14:07 UTC by antooni

2023-07-24 15:15 UTC, luke7211 commented on packages/config/src/layer2s/arbitrum.ts
> +      'TVL includes canonically bridged assets, natively minted assets and externally bridged assets.',
TVL includes canonically bridged assets, native ARB and USDC directly minted on Arbitrum

2023-07-24 15:15 UTC, luke7211 commented on packages/config/src/layer2s/optimism.ts
> +      'TVL includes canonically bridged assets and natively minted assets.',
TVL includes canonically bridged assets and native OP

2023-07-24 15:16 UTC, luke7211 requested changes
Suggested small changes to tooltip text

2023-07-25 10:11 UTC, lucadonnoh approved these changes

2023-07-25 10:13 UTC, merged