Refactor token lists
l2beat/l2beat pull request #1771
Opened 2023-08-07 12:36 UTC by antooni

2023-08-08 13:27 UTC, mateuszradomski requested changes
Either I missed it or we do not have a test that tests if all tokens defined in token.json are CBV?

What about this point `Rename tokenList to canonicalTokensList`?

Are these assumptions meant to be implemented later?
```
// assumptions:
// AssetId needs to be unique, add test for it
// type TokenType = 'Canonical' | 'External' | 'Native'
// type ReportType = TokenType | 'Total'
```

2023-08-09 07:37 UTC, antooni commented on packages/backend/src/core/reports/getEBVConfigHash.ts
>  const EBV_LOGIC_VERSION = 0
no, I have migrated the USDC EBV to the new asset_id

2023-08-09 07:38 UTC, antooni commented on packages/backend/src/core/totalSupply/getTotalSupplyConfigHash.ts
>  const TOTAL_SUPPLY_LOGIC_VERSION = 0
answered above

2023-08-09 07:57 UTC, antooni commented
> Either I missed it or we do not have a test that tests if all tokens defined in token.json are CBV?
> 
> What about this point `Rename tokenList to canonicalTokensList`?
> 
> Are these assumptions meant to be implemented later?
> 
> ```
> // assumptions:
> // AssetId needs to be unique, add test for it
> // type TokenType = 'Canonical' | 'External' | 'Native'
> // type ReportType = TokenType | 'Total'
> ```

For the ValueType refactor the linear task has been created
tokenList is exported as such (because it has all the tokens inside), for canonical there is a method getCanonicalTokens()
thanks for the AssetId test, i have forgot about this one

2023-08-09 08:44 UTC, antooni commented on packages/backend/src/core/assets/ArbitrumEBVUpdater.ts
> +// TODO: Make this class more generic
yup

2023-08-11 11:27 UTC, mateuszradomski approved these changes
I've synced locally and fixed an issue that arose, read the commit message from [a79bce2](https://github.com/l2beat/l2beat/pull/1771/commits/a79bce2f7652604e64b5cb7c8d25d2fe5ca02767) if you want to know more.

From my point of view this is ready to be merged, waiting for a second hand opinion

2023-08-11 12:59 UTC, sz-piotr commented on packages/backend/src/model/Project.ts
> +          ? tokenList.filter((t) => t.type === ValueType.CBV)
We should probably just export `canonicalTokenList`

2023-08-11 13:01 UTC, sz-piotr approved these changes

2023-08-14 06:45 UTC, merged