Backend auto reload and tsconfig refinement
l2beat/l2beat pull request #1785
Opened 2023-08-11 11:55 UTC by sdlyy

## What's changed
- Cleaned up `package.json`
- Refined master `tsconfig.json` file - added few declarations
- Added `ts-node-dev` for backend
- Replaced plain `start:dev`(`node -r src server`) with explicit `ts-node-dev` - transpileNnly mode since typecheck is separate thing here

2023-08-16 09:13 UTC, michalsidzej requested changes
Good change, thanks for taking care of that. Please unclutter tsconfig.json

2023-08-17 07:23 UTC, sdlyy commented on tsconfig.json
> +    "strictPropertyInitialization": true,
https://github.com/l2beat/l2beat/pull/1785/commits/6c22df2eb7f18a542d1f2afd059728b292b15321

2023-08-17 07:24 UTC, sdlyy commented on tsconfig.json
> +    "useUnknownInCatchVariables": true
Not sure what do you mean

2023-08-18 14:16 UTC, michalsidzej approved these changes

2023-08-20 14:25 UTC, merged