OVM icon
l2beat/l2beat pull request #1789
Opened 2023-08-14 13:04 UTC by mateuszradomski

Resolves L2B-2075

2023-08-14 14:12 UTC, luke7211 commented
Boba is also based on old OVM

2023-08-14 14:13 UTC, luke7211 requested changes
add OVM to Boba

2023-08-15 07:48 UTC, lucadonnoh approved these changes

2023-08-15 10:40 UTC, luke7211 approved these changes

2023-08-15 10:41 UTC, merged