Fix tablet view
l2beat/l2beat pull request #1984
Opened 2023-09-28 13:24 UTC by torztomasz

Resolves L2B-2481, L2B-2478

2023-09-29 10:07 UTC, maciekzygmunt requested changes
### There is still an issue with this part of the page. Doesn't look good imo

![image](https://github.com/l2beat/l2beat/assets/77489537/54137de5-0c73-44c7-a48e-a4833594ea0a)

2023-09-29 10:46 UTC, antooni commented
In the description please provide the screenshots of changes (before & after)

2023-10-02 13:30 UTC, torztomasz commented
@antooni @maciekzygmunt Good catch - although we decided with Adi to go with that. There is no other way to make it better than it is implemented currently.

2023-10-02 13:32 UTC, maciekzygmunt approved these changes

2023-10-02 13:36 UTC, merged