Change twitter logo to X
l2beat/l2beat pull request #2013
Opened 2023-10-07 16:45 UTC by gregKlk

I have just changed old twitter logo to X

2023-10-10 12:35 UTC, maciekzygmunt approved these changes

2023-10-10 13:02 UTC, torztomasz requested changes

2023-10-10 13:02 UTC, torztomasz commented on packages/frontend/src/components/icons/products/TwitterIcon.tsx
>      <Icon aria-label="Twitter logo" {...props}>
```suggestion
    <Icon aria-label="X logo" {...props}>
```

2023-10-11 07:37 UTC, torztomasz approved these changes

2023-10-11 07:37 UTC, merged