Add canto as upcoming
l2beat/l2beat pull request #2028
Opened 2023-10-11 11:29 UTC by gregKlk

Hi!
Canto will migrate to be a L2 using Polygon SDK.
I have added its config file.

2023-10-11 14:09 UTC, lucadonnoh requested changes
hey, thanks for the PR! it looks good, can you update the logo to fit a 256x256 png?

2023-10-11 18:45 UTC, gregKlk commented
> hey, thanks for the PR! it looks good, can you update the logo to fit a 256x256 png?

I changed image to be 256x256 png, check my lastest commit.

2023-10-12 10:04 UTC, lucadonnoh approved these changes

2023-10-12 10:07 UTC, lucadonnoh commented
Resolves L2B-2787

2023-10-12 10:10 UTC, merged