Add: Tooltip to TVL Breakdown page
l2beat/l2beat pull request #2050
Opened 2023-10-15 15:36 UTC by Gathin23

## Implementation
This implementation gives the working of tooltip in both light and dark mode colours and the mobile view

![Screenshot_20231015_210026](https://github.com/l2beat/l2beat/assets/94786511/d3cc3464-a9b1-48b7-830a-f7bdf787914f)
![Screenshot_20231015_205921](https://github.com/l2beat/l2beat/assets/94786511/0575b7ec-df17-4bf5-8db8-48440dd459b0)

## Solves
#2035

2023-10-17 14:02 UTC, torztomasz requested changes
Hey! Your PR looks good. Fix two issues mentioned in comment and we can merge it :)

2023-10-17 15:14 UTC, Gathin23 commented on packages/frontend/src/components/tvl-breakdown/TvlBreakdownSummaryBox.tsx
> +          <InfoIcon className="fill-current md:h-3.5 md:w-3.5" />
I removed the fill-current and now the fill be of the same colour as the text as the default colour of the tooltip is same as the text colour used

2023-10-18 06:09 UTC, Gathin23 commented
Did the necessary changes @torztomasz

2023-10-18 08:44 UTC, torztomasz commented
## Desktop
![image](https://github.com/l2beat/l2beat/assets/93620601/06e4e69a-fa52-4eef-a2ad-715b87457140)
Tooltip background color does not match the text

## Mobile
![image](https://github.com/l2beat/l2beat/assets/93620601/86566fb3-18a3-435a-836e-4a3cb8f2e29c)
Tooltip only matches color with the top one


You can check your implementation on a [preview URL](https://l2beat-staging-ey7nh9ru3-l2beat.vercel.app/scaling/projects/arbitrum/tvl-breakdown)

2023-10-18 12:43 UTC, Gathin23 commented
Got it! Will make the necessary changes now @torztomasz

2023-10-18 13:30 UTC, Gathin23 commented
Made the necessary changes @torztomasz 

## Screenshots

![Screenshot_20231018_185442](https://github.com/l2beat/l2beat/assets/94786511/4272a9b3-ab55-4ad9-8dd7-be50c3d97b40)
![Screenshot_20231018_185505](https://github.com/l2beat/l2beat/assets/94786511/c47631b2-046f-479e-b792-e7e1271c837b)
![Screenshot_20231018_185818](https://github.com/l2beat/l2beat/assets/94786511/929d6fc2-1bb1-46c6-bfc6-cb53947768f1)

2023-10-20 08:40 UTC, torztomasz approved these changes

2023-10-20 08:40 UTC, torztomasz commented on packages/frontend/src/components/tvl-breakdown/TvlBreakdownSummaryBox.tsx
> +        tooltip="Total value of natively minted tokens displayed together with a percentage change compared to 7D ago."
Wrong tooltip content

![image](https://github.com/l2beat/l2beat/assets/93620601/20b4f261-f991-48da-9c95-007339af7b76)

2023-10-20 13:14 UTC, Gathin23 commented
A careless copy typo which is now fixed! @torztomasz

2023-10-23 12:47 UTC, torztomasz approved these changes

2023-10-23 12:47 UTC, merged