Add ConfigReader test
l2beat/l2beat pull request #2067
Opened 2023-10-17 13:08 UTC by aminlatifi

Added ConfigReader test
Upgraded discovery dependency
Resolve L2B-2816

2023-10-17 15:23 UTC, adamiak requested changes

2023-10-17 15:23 UTC, adamiak commented on packages/backend/discovery/ConfigReader.test.ts
> +// import { ConfigReader } from './ConfigReader'
Please remove comment.

2023-10-18 09:25 UTC, adamiak requested changes
I suggest renaming `ConfigReader.test.ts` to `verifyConfigs.test.ts` (same in `describe(`). This file is not a proper *unit test* for ConfigReader class, rather it's a validation that config.jsonc files can be parsed.

2023-10-18 12:31 UTC, aminlatifi commented
> I suggest renaming `ConfigReader.test.ts` to `verifyConfigs.test.ts` (same in `describe(`). This file is not a proper _unit test_ for ConfigReader class, rather it's a validation that config.jsonc files can be parsed.

Done

2023-10-20 06:48 UTC, mateuszradomski requested changes

2023-10-20 06:48 UTC, mateuszradomski commented on packages/backend/discovery/verifyConfigs.test.ts
> +  // FIXME: This is a temporary hack to make the tests while configs are in backend
I think we can remove this comment, since the context with which it was written is invalid now

2023-10-23 09:30 UTC, mateuszradomski approved these changes

2023-10-23 09:58 UTC, adamiak approved these changes

2023-10-23 09:58 UTC, merged