Manually verified contracts source link
l2beat/l2beat pull request #2140
Opened 2023-10-31 09:21 UTC by aminlatifi

Changed manuallyVerified json object
Defined schema for manuallyVerify.jsonc

2023-11-23 10:57 UTC, antooni commented on packages/shared-pure/src/types/UrlPath.ts
> +  .refine((data) => /^(https?:\/\/[^\s/$.?#].[^\s]*)$/.test(data), {
Move this check to .schema.json

2023-11-23 11:01 UTC, antooni requested changes
Please either choose parsing via zod or validating via json schema

2023-11-27 15:27 UTC, antooni commented on packages/config/src/verification/verifyManuallyVerifiedContracts.test.ts
This file is not needed, the same test is int the manuallyVerifiedContracts.test.ts

2023-11-27 15:35 UTC, antooni commented on packages/shared-pure/src/types/api/ManuallyVerifiedContrats.ts
> +  ethereumAddressSchema,
`stringAs(EthereumAddress)`

2023-11-27 18:22 UTC, aminlatifi commented on packages/shared-pure/src/types/api/ManuallyVerifiedContrats.ts
> +  ethereumAddressSchema,
Okay, it's fixed now.

2023-11-28 11:22 UTC, merged