Fill projects liveness configs
l2beat/l2beat pull request #2146
Opened 2023-10-31 18:19 UTC by maciekzygmunt

Resolves L2B-2959

2023-11-06 13:34 UTC, antooni requested changes
Check sinceTimestamp:
- transfers - get Timestamp of the first transfer from to
- functionCalls :
 - try to get first call of this method (Etherscan internal calls API?)
 - if you cannot, then check all the timestamps added whether they are all reasonably old

2023-11-09 11:01 UTC, antooni commented on packages/config/src/layer2s/metis.ts
> +        {
delete it

2023-11-09 11:01 UTC, antooni commented on packages/config/src/layer2s/nova.ts
> +          formula: 'functionCall',
should we add 2 more methods to batchSubmissions

2023-11-09 11:03 UTC, antooni commented on packages/config/src/layer2s/linea.ts
> +      batchSubmissions: [],
is it posting txs?

2023-11-09 11:03 UTC, antooni commented on packages/config/src/layer2s/polygonzkevm.ts
> +    liveness: {
double check

2023-11-09 11:04 UTC, antooni commented on packages/config/src/layer2s/arbitrum.ts
> +      batchSubmissions: [
should we add 2 more?

2023-11-10 09:00 UTC, torztomasz approved these changes

2023-11-10 09:08 UTC, merged