zkSync Era state derivation
l2beat/l2beat pull request #2156
Opened 2023-11-02 11:10 UTC by aminlatifi

Added zkSync Era state derivation
Resikves L2B-2958

2023-11-02 14:12 UTC, lucadonnoh requested changes

2023-11-02 14:12 UTC, lucadonnoh commented on packages/config/src/layer2s/zksyncera.ts
> +        rollupNodeSourceAvailable: 'UnderReview',
```suggestion
        rollupNodeSourceAvailable: true,
```

2023-11-02 14:12 UTC, lucadonnoh approved these changes

2023-11-02 14:24 UTC, merged

2023-11-06 11:21 UTC, aminlatifi commented
Resolves L2B-2958