Update the FAQ
l2beat/l2beat pull request #2164
Opened 2023-11-03 14:24 UTC by radinat

Updates the answer for "Why does the Total Value Locked (TVL) on L2BEAT differ from the one on DefiLlama?", which was outdated because of the TVL framework changes.

Resolves L2B-2907

2023-11-03 14:47 UTC, lucadonnoh approved these changes

2023-11-03 14:48 UTC, lucadonnoh requested changes

2023-11-03 14:48 UTC, lucadonnoh commented on packages/frontend/src/pages/faq/getFaqItems.tsx
> +            Example: Let's assume L2BEAT reports a TVL of 2.5 billion, while
```suggestion
            Example: let's assume L2BEAT reports a TVL of 2.5 billion, while
```

2023-11-03 14:48 UTC, lucadonnoh approved these changes

2023-11-06 08:34 UTC, luke7211 approved these changes

2023-11-06 11:15 UTC, merged