add aztec and correct aztec v1
l2beat/l2beat pull request #2171
Opened 2023-11-06 12:18 UTC by catmcgee

2023-11-20 08:00 UTC, lucadonnoh approved these changes

2023-11-20 10:06 UTC, antooni requested changes

2023-11-20 10:06 UTC, antooni commented on packages/config/src/layer2s/aztecv1.ts
> +  id: ProjectId('aztecv1'),
```suggestion
  id: ProjectId('aztec'),
```

2023-11-20 10:06 UTC, antooni commented on packages/config/src/layer2s/aztec.ts
>    id: ProjectId('aztec'),
```suggestion
  id: ProjectId('aztecv2'),
```

2023-11-21 12:01 UTC, lucadonnoh approved these changes

2023-11-21 12:16 UTC, merged