Update Linea
l2beat/l2beat pull request #2226
Opened 2023-11-21 09:44 UTC by mateuszradomski

Resolves L2B-3103

2023-11-21 13:07 UTC, luke7211 commented
Current LINEA setup:

![image](https://github.com/l2beat/l2beat/assets/30408726/b2825ce3-4392-4692-a0dd-6be7d62b08f8)

2023-11-22 07:34 UTC, lucadonnoh commented
new contracts need to be added into the contracts section

2023-11-22 08:22 UTC, luke7211 requested changes
We need to extract roles/permissions from the Module. Given that this module is written using Zodiac standard, we also need to extract Modules from it

2023-12-05 09:29 UTC, luke7211 approved these changes

2023-12-05 09:56 UTC, merged