Add Mint L2
l2beat/l2beat pull request #2359
Opened 2023-12-12 11:04 UTC by zhwindy

This PR Is requesting to update the information of Mint Blockchain on L2Beat.

Mint Blockchain is a Layer 2 network for NFTS.
Homepage: https://www.mintchain.io/
Twitter: https://twitter.com/Mint_Blockchain
Testnet will be launched soon.

2023-12-16 21:29 UTC, enamul1590 commented
https://twitter.com/Enamul1590

2023-12-19 07:06 UTC, 0x1992 commented
Hi @lucadonnoh , can you reveiw this request? 

Mint is the L2 Blockchain for NFTs. Mint blockchain is developed based on OP Stack. Mint Testnet will be launched in Q1 2024.
Website: https://www.mintchain.io/
Twitter: https://twitter.com/Mint_Blockchain

Thanks for your time!

2023-12-19 08:28 UTC, mateuszradomski commented
Hi, please format the `mint.ts` file. You can do that by running `yarn format:fix` in the `config` subpackage

2023-12-19 08:47 UTC, zhwindy commented
> Hi, please format the `mint.ts` file. You can do that by running `yarn format:fix` in the `config` subpackage

ok, the `mint.ts` file is format already.

2023-12-20 13:03 UTC, lucadonnoh requested changes

2023-12-20 13:03 UTC, lucadonnoh commented on packages/frontend/src/static/icons/mint.png
icon should be a 256x256 png

2023-12-20 13:13 UTC, zhwindy commented on packages/frontend/src/static/icons/mint.png
ok, the icon is changed to 256x256 png already

2023-12-20 13:23 UTC, lucadonnoh commented
do you have a live testnet already?

2023-12-20 13:25 UTC, zhwindy commented
> do you have a live testnet already?

we now have an internal testnet, the public testnet is not yet online

2023-12-21 02:02 UTC, zhwindy commented
@lucadonnoh hi, is there any other information that needs to be modified or submitted?

2023-12-21 09:26 UTC, lucadonnoh requested changes

2023-12-21 09:53 UTC, lucadonnoh approved these changes

2023-12-21 10:08 UTC, merged