Add Eclipse
l2beat/l2beat pull request #2429
Opened 2023-12-23 01:17 UTC by sydneyeclipse

2023-12-27 21:15 UTC, mateuszradomski requested changes
Hello,

Please run formatting and linting, check `yarn lint:fix` and `yarn format:fix`. Also make sure that tests are passing for every subpackage

2023-12-27 21:15 UTC, mateuszradomski commented on packages/config/src/layer2s/eclipse.ts
> +const discovery = new ProjectDiscovery('eclipse')
You're not using discovery since your project is still upcoming. You can safely delete this. Otherwise the build is going to fail on you.

2024-01-03 08:24 UTC, lucadonnoh approved these changes

2024-01-03 08:33 UTC, mateuszradomski approved these changes

2024-01-03 08:36 UTC, merged