Hover same address on hover
l2beat/l2beat pull request #2478
Opened 2024-01-04 15:27 UTC by maciekzygmunt

![image](https://github.com/l2beat/l2beat/assets/77489537/f3bc1749-500e-4d75-a3f0-e1de8be8be98)

2024-01-05 09:35 UTC, lucadonnoh commented
looks great! let's make it a bit subtler like in etherscan tho
<img width="181" alt="image" src="https://github.com/l2beat/l2beat/assets/30298476/804f2218-3402-4c34-8184-1a0b9cb10c49">

2024-01-05 23:58 UTC, torztomasz approved these changes

2024-01-05 23:58 UTC, torztomasz commented on packages/frontend/src/components/project/ContractEntry.tsx
>                      !x.isAdmin
`!x.isAdmin && 'text-red-300'`

2024-01-08 08:42 UTC, lucadonnoh requested changes
is this checking the full address or just the text displayed on the website (first few chars and last few chars)? because if that's the case, it could happen that two addresses looks similar but are different and they should not be highlighted together

2024-01-08 08:43 UTC, maciekzygmunt commented
> is this checking the full address or just the text displayed on the website (first few chars and last few chars)? because if that's the case, it could happen that two addresses looks similar but are different and they should not be highlighted together

It is checking the full address

2024-01-08 08:43 UTC, lucadonnoh approved these changes

2024-01-08 10:21 UTC, merged