Update Paradex
l2beat/l2beat pull request #2513
Opened 2024-01-09 12:38 UTC by radinat

Program hash is updated.

Resolves L2B-3507

2024-01-10 11:02 UTC, lucadonnoh requested changes

2024-01-10 11:02 UTC, lucadonnoh commented on packages/backend/discovery/paradex/ethereum/diffHistory.md
> +      values.nonce:
ignore this nonce in config, might be worth giving a name to the Safe first

2024-01-11 12:31 UTC, mateuszradomski approved these changes
lgtm

2024-01-11 12:40 UTC, lucadonnoh approved these changes

2024-01-11 12:43 UTC, merged