Add Ankr and Davos bridge to inReview
l2beat/l2beat pull request #3082
Opened 2024-03-18 12:16 UTC by sekuba

Resolves L2B-4101
Resolves L2B-4100
#2865
#2868

2024-03-18 12:59 UTC, lucadonnoh requested changes

2024-03-18 14:17 UTC, sekuba commented on packages/config/src/bridges/ankr.ts
> +        tokens: ['ANKR'],
we don't support their tokens yet except from this one, should i add the other LSTs they support?

2024-03-18 14:32 UTC, lucadonnoh commented on packages/config/src/bridges/ankr.ts
> +        tokens: ['ANKR'],
yes i think so

2024-03-19 14:24 UTC, lucadonnoh approved these changes

2024-03-19 14:25 UTC, merged