Add Upgrades and Gov section to Polygon zkEvm
l2beat/l2beat pull request #3174
Opened 2024-03-23 08:55 UTC by sekuba

This is an external contribution from @alexhooketh
I reviewed and revised their PR #2816 and the included diagram.

Part of L2B-4521

2024-03-25 09:57 UTC, lucadonnoh requested changes
this is not enough, try to understand how the `updateRollup` function works

2024-03-25 12:42 UTC, sekuba commented
- do you mean that i should further detail how an upgrade would go through the timelock? (schedule...execution)
- or describe how parts can be updated too? (like verifier, root, bridge, PolygonZkEVMEtrog..)? rolluptypeid explanation?
all of it, sth else? :D

2024-03-25 14:43 UTC, sekuba commented
In RollupManager, the `_UPDATE_ROLLUP_ROLE` needed to call 'updateRollup()' is initialized to the timelock.
The AdminMultisig was granted the role tonight though: [in this transaction (through timelock emergency)](https://ethtx.info/mainnet/0xb1f0e00b6642adb65f10521ba7fa349b6aeb0a0e09697057b964eff6324f44c6/), so in the current state i think you are correct (the AdminMultisig can directly update verifier and / or implementation).

But i'm assuming this is only an emergency measure and not the usual path as the emergency state is needed. For this to be correct the `_UPDATE_ROLLUP_ROLE` should be renounced soon by the AdminMultisig though, and i do not understand why the update did not just go through the emergency path of the timelock tonight.

As i understand it i could either describe the state as it was until yesterday, or as it is at the moment (timelock bypassable by admin multisig for upgrades).

2024-03-27 18:10 UTC, lucadonnoh approved these changes

2024-03-27 18:12 UTC, merged