OpStack finality v2
l2beat/l2beat pull request #3193
Opened 2024-03-26 13:43 UTC by michalsidzej

Resolves L2B-4275

## New .env variables  

```
ETHEREUM_BEACON_API_URL=
ETHEREUM_BEACON_API_CALLS_PER_MINUTE=
```
Beacon api url can be the same as rpc url from quicknode.

## Context

This PR introduces decoding of blob data opStack chains to calculate finality. It's still not perfect logic, as we ignore frames that are posted across different batches, but taking it under the consideration requires a different approach to finality.

There's a lot of code that goes over relatively large pieces of data (blobs). I have to say this is my first time working with similar variables, so please don't hesitate to comment on possible improvements. 

## Next steps

Before merging this PR I will disable automatic promote to production on heroku to test if this process is not too memory-intensive

2024-03-27 09:45 UTC, mateuszradomski requested changes

2024-03-27 10:03 UTC, michalsidzej commented on packages/backend/src/modules/finality/analyzers/opStack/decodeSpanBatch.ts
> +  l2BlockTimeSeconds: number
I strongly disagree. https://www.investopedia.com/terms/b/block-time-cryptocurrency.asp#:~:text=Block%20time%20measures%20the%20time,it%20was%20introduced%20in%202009. https://docs.optimism.io/chain/differences#:~:text=Block%20time%20in%20seconds

2024-03-27 10:23 UTC, mateuszradomski commented on packages/backend/src/modules/finality/analyzers/opStack/decodeSpanBatch.ts
> +  l2BlockTimeSeconds: number
Well, I'm not going to be arguing against a standard :p Consider this comment not relevant anymore

2024-03-27 10:47 UTC, michalsidzej commented on packages/backend/src/modules/finality/analyzers/opStack/ChannelBank.ts
> +  // Because we do not look at all the transactions from opStack chains, we ignore this FIFO assumption (could be improved)
[yes sir](https://linear.app/l2beat/issue/L2B-4596/decode-the-proper-channel-data-for-opstack)

2024-03-27 11:03 UTC, michalsidzej commented on packages/backend/src/modules/finality/analyzers/opStack/blobToData.ts
[19d1e94](https://github.com/l2beat/l2beat/pull/3193/commits/19d1e944f7248b80b33aad21ddcf88034dc16634)

2024-03-27 11:03 UTC, michalsidzej commented on packages/backend/src/modules/finality/analyzers/opStack/blobToData.ts
> +  let ipos = 32 // current position into the input blob
[19d1e94](https://github.com/l2beat/l2beat/pull/3193/commits/19d1e944f7248b80b33aad21ddcf88034dc16634)

2024-03-27 11:03 UTC, michalsidzej commented on packages/backend/src/modules/finality/analyzers/opStack/getFrames.ts
> +  const frames = rollupData.slice(1)
[19d1e94](https://github.com/l2beat/l2beat/pull/3193/commits/19d1e944f7248b80b33aad21ddcf88034dc16634)

2024-03-27 11:03 UTC, michalsidzej commented on packages/backend/src/modules/finality/analyzers/opStack/getFrames.ts
> +}
[19d1e94](https://github.com/l2beat/l2beat/pull/3193/commits/19d1e944f7248b80b33aad21ddcf88034dc16634)

2024-03-27 11:03 UTC, michalsidzej commented on packages/backend/src/modules/finality/analyzers/opStack/ChannelBank.ts
> +  // Because we do not look at all the transactions from opStack chains, we ignore this FIFO assumption (could be improved)
[19d1e94](https://github.com/l2beat/l2beat/pull/3193/commits/19d1e944f7248b80b33aad21ddcf88034dc16634)

2024-03-27 17:31 UTC, michalsidzej commented on packages/backend/src/modules/finality/analyzers/opStack/getFrames.ts
> +  )
[1c77105](https://github.com/l2beat/l2beat/pull/3193/commits/1c771052d1007bdb28bb60d790fd4f2adeb4cdc1)

2024-03-27 17:47 UTC, michalsidzej commented on packages/backend/src/modules/finality/analyzers/opStack/utils.ts
> +  const match = str.match(/.{1,2}/g)
[f12a86c](https://github.com/l2beat/l2beat/pull/3193/commits/f12a86c1cd9905b62137ee07b7390b3ef12e74e6)

2024-03-27 18:27 UTC, michalsidzej commented on packages/backend/src/modules/finality/analyzers/opStack/decodeSpanBatch.ts
> +import proto from 'protobufjs'
[f12a86c](https://github.com/l2beat/l2beat/pull/3193/commits/f12a86c1cd9905b62137ee07b7390b3ef12e74e6)

2024-03-28 09:01 UTC, mateuszradomski approved these changes
lgtm

2024-03-28 16:43 UTC, merged