add two new publications
l2beat/l2beat pull request #3296
Opened 2024-04-05 13:43 UTC by Sin-kas

This PR will add governance review #12 and the "how to submit a proposal to arbitrum dao" article

2024-04-05 13:52 UTC, torztomasz commented
wrong thumbnail ratio and title is kinda long ![image](https://github.com/l2beat/l2beat/assets/93620601/084057be-2c12-46f7-b173-f28ae2d4178d)

2024-04-05 14:03 UTC, mateuszradomski requested changes

2024-04-05 14:03 UTC, mateuszradomski commented on packages/frontend/src/content/publications/submitting-a-proposal-to-arbitrum-dao.md
> +1. I**nclude a TL;DR at the top.**
The `I` char is outside the bold, seems like a mistake

2024-04-05 15:30 UTC, torztomasz approved these changes

2024-04-05 15:32 UTC, radinat approved these changes

2024-04-08 08:53 UTC, mateuszradomski approved these changes

2024-04-08 08:54 UTC, merged