update blurb on PHA token bridging mechanism + update links
l2beat/l2beat pull request #3321
Opened 2024-04-08 18:29 UTC by haochizzle

2024-04-09 09:53 UTC, mateuszradomski requested changes

2024-04-09 09:53 UTC, mateuszradomski commented on packages/config/package.json
Why 😭 

Leave this file alone.

2024-04-09 12:59 UTC, haochizzle commented on packages/config/package.json
lol I'll try again. sorry... to me it doesn't seem like I'm making a lot of changes based on the number of lines changed

2024-04-10 18:04 UTC, haochizzle commented on packages/config/package.json
removed the 4 line additions to the packages/config/package.json 

my apologies brother 😭

2024-04-30 07:09 UTC, luke7211 requested changes
fix format

2024-04-30 11:41 UTC, radinat approved these changes

2024-04-30 11:45 UTC, mateuszradomski approved these changes

2024-04-30 11:48 UTC, merged