Rhinofi update: Blocklist implemented
l2beat/l2beat pull request #3374
Opened 2024-04-11 15:40 UTC by sekuba

Resolves L2B-4634

2024-04-12 13:30 UTC, lucadonnoh requested changes
add in the withdrawal section this info and a risk warning

2024-04-13 11:56 UTC, lucadonnoh commented on packages/config/src/common/exits.ts
> +import { text } from 'stream/consumers'
?

2024-04-13 11:58 UTC, lucadonnoh approved these changes

2024-04-13 12:00 UTC, lucadonnoh requested changes
<img width="402" alt="image" src="https://github.com/l2beat/l2beat/assets/30298476/0e31a406-4b4b-465f-82a6-8bc7e1bc061d">
let's also add a phrase here that users can be censored explicitely

2024-04-13 12:00 UTC, sekuba commented
oke

2024-04-13 17:46 UTC, lucadonnoh approved these changes

2024-04-13 17:48 UTC, merged