Add L3 icons next to L3 projects on activity page
l2beat/l2beat pull request #3432
Opened 2024-04-19 09:59 UTC by maciekzygmunt

Resolves L2B-4818

2024-04-22 07:08 UTC, lucadonnoh approved these changes

2024-04-22 12:20 UTC, mateuszradomski requested changes

2024-04-22 12:20 UTC, mateuszradomski commented on packages/frontend/src/components/table/ProjectNameCell.tsx
> +  showIsL3?: boolean
Why do we need this `showIsL3` when we do `showIsL3 && project.type === 'layer3'` anyway?

2024-04-23 07:42 UTC, torztomasz approved these changes

2024-04-23 07:45 UTC, mateuszradomski approved these changes

2024-04-23 07:49 UTC, merged