Add ZK Catalog project page
l2beat/l2beat pull request #3611
Opened 2024-05-07 11:34 UTC by torztomasz

2024-05-10 13:00 UTC, lucadonnoh requested changes

2024-05-10 13:00 UTC, lucadonnoh commented on packages/config/src/projects/types.ts
>    subVerfiers: SubVerfier[]
fix typos pls

2024-05-11 10:35 UTC, lucadonnoh approved these changes

2024-05-13 09:56 UTC, maciekop-l2b approved these changes
LGTM

2024-05-13 10:19 UTC, merged