Use blob data from big query
l2beat/l2beat pull request #3701
Opened 2024-05-15 10:58 UTC by torztomasz

This pull request updates the L2CostsUpdater to fetch blob data from BigQuery instead of using the Ethereum provider. This change improves performance and reduces the number of requests made to the Ethereum provider.

2024-05-15 14:13 UTC, maciekop-l2b requested changes
Nice work! Few nitpicks

2024-05-15 14:13 UTC, maciekop-l2b commented on packages/backend/src/modules/tracked-txs/modules/l2-costs/repositories/L2CostsRepository.ts
> +    await knex.batchInsert('l2_costs', rows, 1000)
Is this change intentional or was changed for debugging purposes?

2024-05-15 14:13 UTC, maciekop-l2b commented on packages/backend/src/modules/tracked-txs/modules/liveness/LivenessUpdater.ts
>      untilTimestamp: UnixTime,
Let's give it a more suitable name like: fromInclusive currently it's very misguiding

2024-05-15 14:13 UTC, maciekop-l2b commented on packages/backend/src/modules/tracked-txs/modules/l2-costs/api/L2CostsController.ts
> +    // Biggest wei we can get from DB is 2^63-1 which divided by 1e18 is safe to parse to Number
Shouldn't this be `1e9` ?

2024-05-15 14:13 UTC, maciekop-l2b commented on packages/backend/src/modules/tracked-txs/modules/l2-costs/indexers/L2CostsAggregatorIndexer.ts
> +    // Biggest wei we can get from DB is 2^63-1 which divided by 1e18 is safe to parse to Number
Shouldn't this be `1e9` ?

2024-05-17 12:04 UTC, torztomasz commented on packages/backend/src/modules/tracked-txs/modules/l2-costs/indexers/L2CostsAggregatorIndexer.ts
> +    // Biggest wei we can get from DB is 2^63-1 which divided by 1e18 is safe to parse to Number
yup

2024-05-17 12:11 UTC, maciekop-l2b approved these changes

2024-05-17 12:15 UTC, merged