Add stricter eslint rules
l2beat/l2beat pull request #378
Opened 2022-01-21 16:40 UTC by antooni

2022-01-21 16:42 UTC, antooni commented
EtherscanClient and CoingeckoClient have typing error in httpClient.fetch(...), timeout is not a property of RequestInit

2022-01-31 18:19 UTC, sz-piotr requested changes

2022-01-31 18:19 UTC, sz-piotr commented on packages/frontend/yarn-error.log
> +Arguments:
Please add yarn-error.log to .gitignore

2022-01-31 18:47 UTC, sz-piotr approved these changes

2022-01-31 18:51 UTC, merged