[L2B-5559] Add last used component for verifiers
l2beat/l2beat pull request #3795
Opened 2024-05-22 14:09 UTC by maciekop-l2b

Resolves L2B-5559

2024-05-22 20:33 UTC, torztomasz requested changes

2024-05-23 06:31 UTC, maciekop-l2b commented on packages/frontend/src/pages/project/zk-catalog/view/Verifiers.tsx
> +                  Descriptions
Fixed

2024-05-23 06:33 UTC, maciekop-l2b commented on packages/frontend/src/build/api/fetchVerifiersApi.ts
> +function getVerifiersApiResponse(): VerifiersApiResponse {
Fixed

2024-05-23 06:39 UTC, maciekop-l2b commented on packages/frontend/src/pages/project/zk-catalog/props/getProps.ts
>      linkToMainProjectDetails: `/scaling/projects/${project.display.slug}`,
done

2024-05-23 06:46 UTC, torztomasz commented on packages/frontend/src/pages/project/zk-catalog/props/getProps.ts
> +        : undefined,
```suggestion
    linkToMainProjectDetails:
      project.type === 'zk-catalog'
        ? undefined
        : `/scaling/projects/${project.display.slug}`,
```

2024-05-23 06:46 UTC, torztomasz approved these changes

2024-05-23 06:53 UTC, merged