Display out of sync activity chart
l2beat/l2beat pull request #3818
Opened 2024-05-23 10:02 UTC by torztomasz

2024-06-13 08:23 UTC, sz-piotr requested changes

2024-06-13 08:23 UTC, sz-piotr commented on packages/frontend/src/scripts/charts/renderer/getPointGroups.test.ts
> +describe(getPointGroups.name, () => {
You could make the assumption that dashed is only at the end and simplify the code.
Also each line can be dashed/not separately.
Also, how does this work for stacked chart?

2024-06-17 12:14 UTC, sz-piotr commented on packages/frontend/src/scripts/charts/view-controller/charts/getActivityRenderParams.ts
> +      const isOutOfSync = timestamp > 1708683180
Is this supposed to be commented out?

2024-06-17 12:14 UTC, sz-piotr approved these changes

2024-06-17 12:39 UTC, torztomasz commented on packages/frontend/src/scripts/charts/view-controller/charts/getActivityRenderParams.ts
> +      const isOutOfSync = timestamp > 1708683180
I left it just for preview

2024-06-17 12:46 UTC, merged