Add sanko chain full
l2beat/l2beat pull request #3899
Opened 2024-05-27 18:17 UTC by sekuba

Caldera orbit stack l3 with rari's implementation contracts
custom native token DMT
Admin eoa
AnyTrust 1/1

Closes L2B-4658

2024-05-27 18:34 UTC, lucadonnoh requested changes

2024-05-27 18:34 UTC, lucadonnoh commented on packages/config/src/projects/layer3s/sanko.ts
> +      tokens: ['*'],
```suggestion
      tokens: '*',
```

2024-05-27 18:39 UTC, sekuba commented
not sure how this affects tvl2 so will merge tomorrow morning?

2024-05-28 10:49 UTC, lucadonnoh approved these changes

2024-05-28 10:51 UTC, merged