da-beat template
l2beat/l2beat pull request #4031
Opened 2024-06-05 13:47 UTC by sdlyy

2024-06-11 11:10 UTC, torztomasz approved these changes

2024-06-11 11:16 UTC, torztomasz requested changes

2024-06-11 11:16 UTC, torztomasz commented on packages/frontend2/src/app/(new)/data-availability/_utils/getDaRiskView.ts
> +}
include in config

2024-06-12 10:16 UTC, sdlyy commented on packages/config/src/projects/other/da-beat/types/DaBridge.ts
> +    logo?: string
Not now, removed

2024-06-12 10:16 UTC, sdlyy commented on packages/config/src/projects/other/da-beat/types/DaLayer.ts
> +    logo?: string
Not now, removed

2024-06-12 10:16 UTC, sdlyy commented on packages/frontend2/src/app/(new)/data-availability/_utils/getDaRiskView.ts
> +}
Fixed and unified

2024-06-12 10:21 UTC, torztomasz approved these changes

2024-06-12 10:26 UTC, merged