improve BridgesMvpWarning ux
l2beat/l2beat pull request #4166
Opened 2024-06-13 02:54 UTC by hello-jdj

Using "Discord" with a capital "D" since it is a proper noun referring to the specific platform. Make it clickable.

### Before
<img width="1205" alt="image" src="https://github.com/l2beat/l2beat/assets/172093886/09f47673-e1d3-4eb9-93d5-d41ff1731d79">

### After
<img width="1208" alt="image" src="https://github.com/l2beat/l2beat/assets/172093886/0fdca413-3cb5-4d28-aedb-16cce46250d1">

2024-06-13 07:20 UTC, torztomasz requested changes

2024-06-13 07:20 UTC, torztomasz commented on packages/frontend/src/components/BridgesMvpWarning.tsx
> +      >
use our Link component with proper type

2024-06-13 10:56 UTC, hello-jdj commented on packages/frontend/src/components/BridgesMvpWarning.tsx
> +      >
Gotcha, updated!

2024-06-18 06:43 UTC, torztomasz approved these changes

2024-06-18 06:45 UTC, merged