Refactor TrackedTxsIndexer using ManagedMultiIndexer
l2beat/l2beat pull request #4219
Opened 2024-06-19 12:14 UTC by maciekzygmunt

Resolves L2B-4905

2024-07-02 13:10 UTC, maciekop-l2b requested changes
Great work!

Some minor things to correct.

2024-07-02 13:10 UTC, maciekop-l2b commented on packages/database/src/l2-cost/repository.ts
>    async getWithProjectIdByTimeRange(timeRange: [UnixTime, UnixTime]) {
Let's apply the same changes as suggested for knex repo

2024-07-02 13:10 UTC, maciekop-l2b commented on packages/database/src/liveness/repository.ts
>    async getWithSubtypeDistinctTimestamp(projectId: ProjectId) {
Let's apply the same changes as suggested for knex repo

2024-07-04 08:45 UTC, antooni commented on packages/backend/src/modules/tracked-txs/TrackedTxsIndexer.ts
> +    const logger = $.logger.tag(name)
is this additional tagging needed?

2024-07-04 11:29 UTC, maciekop-l2b approved these changes

2024-07-04 12:30 UTC, antooni approved these changes

2024-07-04 12:36 UTC, merged