add arcology
l2beat/l2beat pull request #4242
Opened 2024-06-21 06:21 UTC by sameplacewei

add arcology

2024-06-21 06:55 UTC, sameplacewei reviewed
reviewed

2024-06-21 09:48 UTC, lucadonnoh requested changes
remove tech provider. we will add it when there are at least two chains using it

2024-06-21 10:07 UTC, sameplacewei commented
If this provider is removed, what will our project use as provider？

2024-06-21 10:37 UTC, lucadonnoh commented
> If this provider is removed, what will our project use as provider？

nothing, like many others

2024-06-24 08:52 UTC, lucadonnoh commented on packages/config/src/common/ScalingProjectProvider.ts
> +  | 'Arcology'
```suggestion
```

2024-06-24 08:53 UTC, lucadonnoh requested changes

2024-06-24 08:53 UTC, lucadonnoh commented on packages/config/src/common/ScalingProjectProvider.ts
> +  | 'Arcology'
```suggestion
```

2024-06-26 14:40 UTC, lucadonnoh commented on packages/config/src/common/ScalingProjectProvider.ts
> +  | 'Arcology'
pls remove this one since not used

2024-06-26 14:41 UTC, lucadonnoh commented on packages/config/src/projects/layer2s/arcology.ts
> +    provider: 'Arcology',
```suggestion
```

2024-06-26 15:08 UTC, sameplacewei commented on packages/config/src/projects/layer2s/arcology.ts
> +    provider: 'Arcology',
OK，I have fixed it.

2024-06-27 07:10 UTC, lucadonnoh commented on packages/config/src/common/ScalingProjectProvider.ts
> +  | 'Arcology'
ser

2024-07-02 13:49 UTC, lucadonnoh approved these changes

2024-07-02 14:52 UTC, merged