Port risk analysis page
l2beat/l2beat pull request #4435
Opened 2024-07-11 07:57 UTC by imxeno

2024-07-16 13:21 UTC, torztomasz requested changes

2024-07-16 13:21 UTC, torztomasz commented on packages/frontend2/src/app/_components/table/basic-table.tsx
> +    isPinned === 'right' && column.getIsFirstColumn('right')
```suggestion
  const isPinned = column.getIsPinned()
  if(!isPinned) {
  	return undefined
  }
  
  const isLastLeftPinnedColumn =
    isPinned === 'left' && column.getIsLastColumn('left')
  const isFirstRightPinnedColumn =
    isPinned === 'right' && column.getIsFirstColumn('right')
```

2024-07-16 13:21 UTC, torztomasz commented on packages/frontend2/src/app/_components/table/basic-table.tsx
> +                style={{ ...getCommonPinningStyles(header.column) }}
why spreading if you can simply do this?
```suggestion
                style={getCommonPinningStyles(header.column)}
```

2024-07-16 13:21 UTC, torztomasz commented on packages/frontend2/src/app/_components/table/basic-table.tsx
> +                    style={{ ...getCommonPinningStyles(cell.column) }}
same

2024-07-16 13:28 UTC, imxeno commented on packages/frontend2/src/app/(new)/(other)/_components/scaling-filters.tsx
> +      (item) => (item.type === 'layer3' && item.hostChainName) || 'Ethereum',
It's different because of the `ScalingRiskEntry` type.

2024-07-16 13:35 UTC, imxeno commented on packages/frontend2/src/app/(new)/(other)/_components/scaling-filters.tsx
> +      (item) => (item.type === 'layer3' && item.hostChainName) || 'Ethereum',
Anyway, I restored the old fn.

2024-07-18 06:30 UTC, torztomasz approved these changes

2024-07-18 07:13 UTC, merged