Implement activity repository
l2beat/l2beat pull request #4531
Opened 2024-07-18 11:18 UTC by maciekzygmunt

Resolves L2B-6164

2024-07-18 11:45 UTC, antooni commented on packages/database/src/activity/repository.test.ts
> +  const DATA: ActivityRecord[] = [
get rid of this globabl DATA object and write test in a similiar fashion to AmountsRepository, where you create each mock inline - it is more readable

2024-07-18 13:04 UTC, maciekop-l2b commented on packages/database/prisma/schema.prisma
> +  @@index([projectId], map: "activity_project_id_index")
Do we need this index name mapping?

2024-07-18 13:10 UTC, maciekop-l2b requested changes

2024-07-18 13:10 UTC, maciekop-l2b commented on packages/database/src/activity/repository.ts
> +          eb('timestamp', '<=', to.toDate()),
IMHO we  should be only one-sided inclusive
```suggestion
          eb('timestamp', '<', to.toDate()),
```

2024-07-22 08:12 UTC, maciekop-l2b approved these changes

2024-07-22 08:37 UTC, merged