Fix missing provider consideration in type sort sorting logic
l2beat/l2beat pull request #5162
Opened 2024-09-19 12:54 UTC by hyperchris123

Currently, the type sort function only sorts by category, leading to inconsistent ordering when provider is not taken into account. 
This fix introduces sorting by both category and provider to ensure the correct order and eliminate sorting issues.

### Before
<img width="1209" alt="image" src="https://github.com/user-attachments/assets/b13ec818-291a-4b05-9534-f753dd8f8c60">

### After
<img width="1193" alt="image" src="https://github.com/user-attachments/assets/a74d1764-477f-4f12-9e7c-57c0238fb396">

2024-10-08 08:36 UTC, torztomasz requested changes
![image](https://github.com/user-attachments/assets/5f8e66a1-da74-41df-b4d9-05fe456b1b3c)

Projects without providers should also be grouped

2024-10-08 08:36 UTC, torztomasz commented on packages/frontend/src/app/(side-nav)/scaling/summary/_components/table/columns.tsx
> +    },
let's extract the fn to separate file called `order-by-category-and-provider` or smth

2024-10-08 08:54 UTC, lucadonnoh commented
my opinion is that projects should be sorted by column order first and then tvl

2024-10-11 16:58 UTC, lucadonnoh commented
imo not needed, @torztomasz feel free to reopen if you think otherwise

2024-10-11 16:58 UTC, closed without merging