Add createdAt and sort upcoming by it
l2beat/l2beat pull request #5231
Opened 2024-09-26 10:13 UTC by torztomasz

2024-09-26 10:18 UTC, imxeno requested changes

2024-09-26 10:18 UTC, imxeno commented on packages/frontend/src/server/features/scaling/upcoming/get-scaling-upcoming-entries.ts
> +      assert(a.createdAt && b.createdAt, 'Project has no createdAt')
:eyes:

2024-09-26 10:23 UTC, sz-piotr requested changes

2024-09-26 10:23 UTC, sz-piotr commented on packages/frontend/src/server/features/scaling/upcoming/get-scaling-upcoming-entries.ts
> +      console.log(a.createdAt, b.createdAt)
Remove

2024-09-26 10:25 UTC, sz-piotr requested changes

2024-09-26 10:25 UTC, sz-piotr commented on packages/frontend/package.json
> +    "project-creation-dates": "node --loader esbuild-register/loader -r esbuild-register scripts/project-creation-dates.ts"
Remove

2024-09-26 10:25 UTC, imxeno submitted a review, later dismissed

2024-10-09 13:16 UTC, maciekzygmunt approved these changes

2024-10-09 13:31 UTC, merged