Add Allo as upcoming project
l2beat/l2beat pull request #5251
Opened 2024-09-29 17:01 UTC by QuantumFatima

2024-09-30 08:52 UTC, lucadonnoh requested changes

2024-09-30 08:52 UTC, lucadonnoh commented on packages/config/src/projects/layer2s/allo.ts
> +      'Allo is an OP Stack L2 which will be a part of Super Chain. It is used to tokenize Real World Assets seamlessly - unlocking reduced transaction times, lower costs, and enhanced security.',
```suggestion
      'Allo is an OP Stack L2 which will be a part of Superchain. It is used to tokenize Real World Assets seamlessly - unlocking reduced transaction times and lower costs.',
```

2024-10-01 07:32 UTC, lucadonnoh commented
please fix tests

2024-10-02 16:26 UTC, QuantumFatima commented
> please fix tests

@lucadonnoh I have tried to run the yarn check-verified-contracts command but got errors in my terminal and I do not know how to fix them.

2024-10-11 17:02 UTC, merged