Update the Activity page to show UOPS metrics
l2beat/l2beat pull request #5513
Opened 2024-10-21 11:43 UTC by maciekzygmunt

Resolves L2B-7792

2024-10-22 11:03 UTC, torztomasz requested changes

2024-10-22 11:03 UTC, torztomasz commented on packages/frontend/src/components/chart/activity/project-activity-chart.tsx
> +              <span className="max-lg:hidden">ETH Mainnet Operations</span>
I guess it should be user operations

2024-10-22 11:03 UTC, torztomasz commented on packages/frontend/src/components/chart/activity/activity-chart.tsx
> +                <span className="hidden md:inline">ETH Mainnet Operations</span>
I guess it should be user operations

2024-10-22 11:03 UTC, torztomasz commented on packages/frontend/src/utils/number-format/format-uops-ratio.ts
> +  }
STOP PLS

2024-10-22 11:03 UTC, torztomasz commented on packages/frontend/src/utils/number-format/format-uops-ratio.ts
> +  }
```suggestion
  if (ratio < 1.01) {
    return '<1.01'
  }
  
  return formatNumber(ratio, 2)
```

2024-10-22 11:33 UTC, lucadonnoh commented on packages/frontend/src/utils/number-format/format-uops-ratio.ts
> +  }
lmaoooooooo

2024-10-22 12:12 UTC, torztomasz approved these changes

2024-10-31 10:45 UTC, radinat requested changes

2024-10-31 10:45 UTC, radinat commented on packages/frontend/src/app/(side-nav)/scaling/activity/_components/table/columns.tsx
> +        'The ratio of user operations to transactions over the past day.',
```suggestion
        'The ratio of user operations to transactions over the past day. A high ratio indicates that most transactions contain multiple user operations bundled into a single transaction.' ,
```

2024-10-31 11:53 UTC, radinat requested changes

2024-10-31 11:53 UTC, radinat commented on packages/frontend/src/app/(side-nav)/scaling/activity/_components/table/columns.tsx
> +        'The ratio of user operations to transactions over the past day. A high ratio indicates that most transactions contain multiple user operations bundled into a single transaction.',
```suggestion
        'The ratio of user operations to transactions over the past day. A high ratio indicates that for some transactions multiple individual user operations are bundled in a single transaction.',
```

2024-11-20 13:44 UTC, torztomasz requested changes

2024-11-20 13:44 UTC, torztomasz commented on packages/frontend/src/app/(side-nav)/scaling/_components/scaling-activity-filters.tsx
> +        'flex flex-col-reverse gap-x-4 gap-y-2 [@media(min-width:1000px)]:flex-row [@media(min-width:1000px)]:justify-between',
container queries mb?

2024-11-20 13:44 UTC, torztomasz commented on packages/frontend/src/app/(side-nav)/scaling/activity/_components/table/max-uops-cell.tsx
> +export function MaxUopsCell({ maxUops, timestamp }: Props) {
its not only UOPS but also TPS, name should be somehow unified

2024-11-20 13:44 UTC, torztomasz commented on packages/frontend/src/app/(side-nav)/scaling/summary/_components/table/columns.tsx
> +          {formatUops(ctx.getValue())}
this fn is probably also used with TPS so it should have universal name

2024-11-21 10:49 UTC, torztomasz approved these changes

2024-11-21 10:57 UTC, merged