Improve sorting
l2beat/l2beat pull request #5572
Opened 2024-10-24 13:05 UTC by torztomasz

Resolves L2B-7821, L2B-7820

2024-10-24 16:05 UTC, lucadonnoh requested changes
\# and Names don’t sort correctly

2024-10-28 17:00 UTC, lucadonnoh submitted a review, later dismissed

2024-10-29 09:47 UTC, imxeno approved these changes

2024-10-29 09:47 UTC, imxeno commented on packages/frontend/src/components/table/sorting/functions/sort-by-sentiment-and-dac-members.ts
> +])
👀

2024-10-29 09:47 UTC, imxeno commented on packages/frontend/src/components/table/sorting/functions/sort-by-dac-members.ts
> +])
👀

2024-10-29 10:25 UTC, merged