Discodrive base
l2beat/l2beat pull request #5682
Opened 2024-11-01 12:27 UTC by sekuba

This makes base permissions and contracts discoveryDriven and renames the Foundation Multisigs.

2024-11-01 13:35 UTC, lucadonnoh requested changes

2024-11-01 13:35 UTC, lucadonnoh commented on packages/backend/discovery/base/ethereum/diffHistory.md
> +Provide description of changes. This section will be preserved.
😳

2024-11-01 13:38 UTC, sekuba commented on packages/backend/discovery/base/ethereum/diffHistory.md
> +Provide description of changes. This section will be preserved.
😳

2024-11-02 03:45 UTC, lucadonnoh approved these changes

2024-11-02 04:03 UTC, merged