Add fluence (full)
l2beat/l2beat pull request #5750
Opened 2024-11-06 13:35 UTC by sekuba

Closes L2B-8035

2024-11-06 16:12 UTC, lucadonnoh requested changes

2024-11-06 16:12 UTC, lucadonnoh commented on packages/backend/discovery/fluence/ethereum/diffHistory.md
> +Provide description of changes. This section will be preserved.
meow

2024-11-06 16:13 UTC, lucadonnoh commented
rest lgtm

2024-11-06 16:19 UTC, sekuba commented on packages/backend/discovery/fluence/ethereum/diffHistory.md
> +Provide description of changes. This section will be preserved.
![grafik](https://github.com/user-attachments/assets/814d1273-0c1b-40e9-af75-8426ddf810bf)

2024-11-06 16:28 UTC, lucadonnoh approved these changes

2024-11-06 16:30 UTC, merged

2024-11-13 23:35 UTC, Danni1326 approved these changes

2024-11-13 23:35 UTC, Danni1326 approved these changes