Update Summary page TVL chart
l2beat/l2beat pull request #6099
Opened 2024-12-12 11:09 UTC by maciekzygmunt

Resolves L2B-8503

2024-12-16 10:51 UTC, torztomasz requested changes

2024-12-16 14:02 UTC, torztomasz requested changes

2024-12-16 14:02 UTC, torztomasz commented on packages/frontend/src/server/features/scaling/tvl/utils/get-tvl-projects.ts
> +      return 'Others'
make those expected as return type

2024-12-16 14:11 UTC, torztomasz approved these changes

2024-12-18 11:46 UTC, lucadonnoh commented
can you also make this chart use the same color for Validiums & Optimiums as in the summary page? for consistency

<img width="652" alt="image" src="https://github.com/user-attachments/assets/49139f39-409b-4e50-920c-9a48493be02a" />

2024-12-19 08:31 UTC, torztomasz requested changes

2024-12-19 08:31 UTC, torztomasz commented on packages/frontend/src/components/chart/activity/activity-chart-hover.tsx
> +    case undefined:
why is this a case for undefined?

2024-12-19 08:31 UTC, torztomasz commented on packages/frontend/src/components/chart/activity/scaling-summary-activity-chart.tsx
> +        />
we can keep it but composition would be nicer

2024-12-19 08:31 UTC, torztomasz commented on packages/frontend/src/components/chart/core/chart-legend.tsx
> +          <div className={cn('size-[10px] rounded-sm', e.color)} />
```suggestion
          <div className={cn('size-2.5 rounded-sm', e.color)} />
```

2024-12-19 08:31 UTC, torztomasz commented on packages/frontend/src/components/chart/tvl/scaling-summary-tvl-chart.tsx
> +function RecategorizedChart({
should be `RecategorisedTvlChart`

2024-12-19 08:31 UTC, torztomasz commented on packages/frontend/src/server/features/scaling/activity/get-recategorized-activity-chart.ts
> +          ethereumCount,
what about tps?

2024-12-19 08:31 UTC, torztomasz commented on packages/frontend/src/styles/globals.css
> +    --success-positive: #15ca60;
not in this PR but change it to positive (accepted by Jan)

2024-12-19 08:48 UTC, torztomasz approved these changes

2024-12-19 08:53 UTC, merged