Topbar redesign
l2beat/l2beat pull request #644
Opened 2022-09-15 08:23 UTC by sin6pi7

- Move NavBar outside of body container
- Redesign top banner
- Update spacing and colors
- Update icons

2022-09-15 09:37 UTC, krzkaczor approved these changes
I reviewed only visual aspect of this PR 👍

2022-09-15 10:18 UTC, sz-piotr requested changes
The site scrolls horizontally on smaller screens
<img width="343" alt="Screenshot 2022-09-15 at 12 18 51" src="https://user-images.githubusercontent.com/17070569/190379441-53ffb67f-573b-42c2-86fb-96d0812443b5.png">

2022-09-15 10:27 UTC, sz-piotr commented
Also on mobile the sidebar doesn't align with the banner
<table>
<tr>
<td>
<img width="343" alt="Screenshot 2022-09-15 at 12 26 55" src="https://user-images.githubusercontent.com/17070569/190381047-d8c7076c-8663-46e3-a5c8-29d9aec8bc55.png">
</td>
<td>
<img width="343" alt="Screenshot 2022-09-15 at 12 26 34" src="https://user-images.githubusercontent.com/17070569/190380964-9fa61dea-269b-44ec-80f4-ea38db81a22f.png">
</td>
</tr>
</table>

2022-09-15 10:32 UTC, sin6pi7 commented
@sz-piotr fixed both

2022-09-16 07:10 UTC, sz-piotr requested changes

2022-09-16 07:10 UTC, sz-piotr commented on packages/frontend/src/components/navbar/SidebarMenu.tsx
> +          'hidden fixed top-[32px] left-0 z-50',
Would be good to have this conditional on config. Also 32px is part of tailwind's scale so you could use top-8

2022-09-16 07:55 UTC, sz-piotr approved these changes

2022-09-16 09:33 UTC, merged