Wait until queue is empty
l2beat/l2beat pull request #747
Opened 2022-10-04 14:10 UTC by sin6pi7

2022-10-04 15:05 UTC, sz-piotr approved these changes

2022-10-04 19:22 UTC, krzkaczor requested changes

2022-10-04 19:22 UTC, krzkaczor commented on packages/backend/src/core/transaction-count/RpcTransactionUpdater.ts
> +    await this.blockQueue.waitTilEmpty()
this deserves a long comment on why it's so important to wait until the queue is empty :)

2022-10-05 08:21 UTC, krzkaczor approved these changes

2022-10-05 08:30 UTC, merged