Add near rainbow bridge info
l2beat/l2beat pull request #749
Opened 2022-10-04 14:45 UTC by luke7211

2022-10-04 20:16 UTC, sz-piotr requested changes

2022-10-04 20:16 UTC, sz-piotr commented on packages/config/src/bridges/near.ts
> +/*
Please remove the code comment

2022-10-05 05:56 UTC, luke7211 commented on packages/config/src/bridges/near.ts
> +/*
Removed

2022-10-05 05:59 UTC, luke7211 commented on packages/config/src/bridges/near.ts
> +/*
Comment removed

2022-10-05 13:20 UTC, sz-piotr approved these changes

2022-10-06 06:47 UTC, merged