Add Omni bridge details.
l2beat/l2beat pull request #779
Opened 2022-10-06 14:57 UTC by adamiak

Resolves L2B-203

2022-10-06 18:21 UTC, luke7211 requested changes
Expand section on "investing" bridge funds

2022-10-09 11:08 UTC, sz-piotr commented
I have update the risk view descriptions to be in line with https://github.com/l2beat/l2beat/pull/794. Please check if the changes are correct before proceeding

2022-10-10 14:05 UTC, sz-piotr requested changes

2022-10-10 14:05 UTC, sz-piotr commented on packages/config/src/tokens.ts
> +  {
Remove all new tokens because they do not comply with our policy

2022-10-10 14:13 UTC, sz-piotr requested changes

2022-10-10 14:13 UTC, sz-piotr commented on packages/config/src/bridges/omni.ts
> +      ...RISK_VIEW.WRAPPED,
canonical

2022-10-11 07:32 UTC, sz-piotr approved these changes

2022-10-11 07:45 UTC, merged