Add Gravity
l2beat/l2beat pull request #790
Opened 2022-10-07 14:33 UTC by antooni

2022-10-07 18:14 UTC, luke7211 requested changes
Check current token list and add major tokens missing (USDT, WBTC, maybe PSTAKE)

2022-10-09 11:07 UTC, sz-piotr commented
I have update the risk view descriptions to be in line with #794. Please check if the changes are correct before proceeding

2022-10-10 12:19 UTC, antooni commented
I decided not to include PSTAKE because it is currently 635th by mc on coingecko, so it fells below our top-300 coingecko criteria

2022-10-10 14:25 UTC, sz-piotr commented on packages/config/src/bridges/gravity.ts
> +        'Control Gravity contract on Ethereum, funds cannot be transfer without the signature of at least 2/3 of the validators set.',
How does Ethereum know who the 2/3 are

2022-10-10 15:08 UTC, luke7211 approved these changes

2022-10-10 15:27 UTC, merged