Add second line to activity chart
l2beat/l2beat pull request #818
Opened 2022-10-12 15:04 UTC by michalsidzej

Resolves L2B-195

Styling of toggle will be part of L2B-191
<img width="1184" alt="Screenshot 2022-10-12 at 17 01 40" src="https://user-images.githubusercontent.com/38423054/195378431-5d980f7e-e866-4f7d-93a9-a249a03cfe71.png">

2022-10-13 09:07 UTC, michalsidzej commented on packages/frontend/src/components/chart/Chart.tsx
> +  hasActivity,
Oh, that's true, I completely forgot that we have one

2022-10-13 09:08 UTC, michalsidzej commented on packages/frontend/src/components/chart/configure/draw/path.ts
> +export function path(
How about `pointsPath`?

2022-10-13 09:12 UTC, michalsidzej commented on packages/frontend/src/components/chart/Chart.tsx
> +        <EthereumActivityToggle showToggle={type === 'activity'} />
This will be a part of [L2B-236](https://linear.app/l2beat/issue/L2B-236/re-introduce-time-and-scale-controls-to-activity-chart)

2022-10-13 17:40 UTC, michalsidzej commented on packages/frontend/src/components/chart/Chart.tsx
> +        <EthereumActivityToggle showToggle={type === 'activity'} />
Ok, it has it now actually

2022-10-14 06:12 UTC, sz-piotr requested changes

2022-10-14 06:12 UTC, sz-piotr commented on packages/frontend/src/components/IncludeLayer2sCheckbox.tsx
> +      text="Include canonical bridges to Layer2s"
Rename text to label?

2022-10-14 06:12 UTC, sz-piotr commented on packages/frontend/src/components/Checkbox.tsx
> +  text: string
label: ReactNode

2022-10-14 06:12 UTC, sz-piotr commented on packages/frontend/src/components/chart/EthereumActivityToggle.tsx
> +      className={className}
```suggestion
  return (
    <Checkbox
      className={cx(!props.showToggle && 'hidden')}
```

2022-10-14 06:12 UTC, sz-piotr commented on packages/frontend/src/components/chart/configure/plot.ts
> +      },
```suggestion
      { fade: true },
```

2022-10-14 06:29 UTC, sz-piotr approved these changes

2022-10-14 06:47 UTC, merged