Add Eth line icon
l2beat/l2beat pull request #850
Opened 2022-10-19 05:41 UTC by michalsidzej

2022-10-19 07:13 UTC, sz-piotr requested changes

2022-10-19 07:13 UTC, sz-piotr commented on packages/frontend/src/components/icons/chart/EthereumLineIcon.tsx
> +      <rect width="10" height="6" fill="#53A2FF" />
we can specify the fill using a tailwind class like `fill-blue-???`

2022-10-19 16:41 UTC, sin6pi7 approved these changes

2022-10-20 08:09 UTC, sz-piotr approved these changes

2022-10-24 12:02 UTC, merged